### PR TITLE
feat: Add option to change default volume

### PR DESCRIPTION
**Pull request by TannerGabriel**
Add the option to adjust the default volume of the player inside `config.json`.

Resolves: #263

### CODE REVIEW

**Comment by elboletaire** [comment]
Haven't tried it yet, but I don't see the `/volume` command storing the value. Don't you think it makes total sense to store it when using the volume command?

**Comment by elboletaire** [comment]
I don't share that idea about the volume for the queue... I do understand it, but I don't share it, since usually the problem is not from an entire queue, but from a single song... so if the volume does reset on every song, that would make sense to not store it to the settings, but considering we're talking about a volume setting being reused only during the first play in the queue... I personally would share that and use `/volume` to set the volume both in settings.json and in memory for the current plays.

There's also the issue about the bot not disconnecting anymore, so the volume stored is in fact reused for consequent queues.

**Comment by elboletaire** [comment]
@TannerGabriel what do you think about adding a package like `conf` for managing (reading and writing) the configuration? https://www.npmjs.com/package/conf

I may be able to make a PR during the next two weeks (not too much free time these days...). If you agree using the package I would using just for the volume for now, following the behavior I described above (reusing the `/volume` command to store it directly into the settings file, and read from that file every time `player.play` command is executed).

**Comment by TannerGabriel** [comment]
Apologies for the delayed reply, @elboletaire. I've been tied up and couldn't get around to this until now. 

Your suggestion on maintaining the volume makes sense, and I'm on board with modifying the existing command, provided we update the README accordingly. 

The `conf` package seems suitable, so let's proceed with that. Would you like to make a PR, or should I go ahead and update this PR?

**Comment by elboletaire** [comment]
> The `conf` package seems suitable, so let's proceed with that. Would you like to make a PR, or should I go ahead and update this PR?

Please, go ahead!

**Comment by TannerGabriel** [comment]
Implementation should be ready for review.

**Review by elboletaire — APPROVED** [review]
LGTM. It calls my attention the async import of `conf` in the volume command. I would import it normally, but maybe you have your reasons (?) I understand you want to avoid loading the conf package unless it's really used, but I'm not sure of the actual purpose of doing this.

**Comment by TannerGabriel** [comment]
Currently, the files are CommonJS modules, which is why I use the `require` syntax to import packages. The `conf` package does not seem to support this syntax (only supports ESM) and therefore needs to be imported dynamically.

I will probably refactor the whole bot to ES modules in the future. After that, we should be able to import `conf` using `import {Conf} from 'conf'`.

**Comment by elboletaire** [comment]
Ah, that makes total sense. BTW looks like the docker image failed with a random connection error to npmjs (?)

**Comment by TannerGabriel** [comment]
Thanks for the notice. Yes, it seemed to be a connection error, but re-running didn't seem to fix the problem. Since I used deprecated versions of all the actions I used the opportunity to update the actions and it seems to work again.

**Pull request merged**
