### PR TITLE
fix: Bot not disconnecting after queue finished

### PR DESCRIPTION
**Pull request by TannerGabriel**
Delete queue when receiving the `emptyQueue` event so that the bot disconnects from the voice channel.

### CODE REVIEW

**Comment by TannerGabriel** [comment]
@elboletaire can you please validate that this fixes the disconnect problem you mentioned in #264

**Comment by TannerGabriel** [comment]
Thanks for the quick response and willingness to test, but you can take your time with it since it is nothing time-critical; a few days or a week are totally fine. I can also merge it without you testing since it worked on my machine - however you prefer.

**Comment by elboletaire** [comment]
I'd say to merge it then, I'll also be able to test it more easily once we have the docker image published ;)

**Comment by elboletaire** [comment]
update: works like a charm 👌🏽

**Pull request merged**
